import { expect, it, vi } from "vitest";
import { createStudentSessionCsrfToken, StudentSessionCsrf } from "../../src/http/student-session-csrf";
import { isCanonicalToken } from "../../src/infrastructure/student-session-cookie";

const origin = "https://nssscdl.test";
const raw = "A".repeat(43);
// Independent known SHA-256 vector, not generated by the implementation.
const expected = "p35EDD5VELmGsajOaMrGPH6WzW74IYQLZ9g-3qTG_74";
const request = (value = expected) => new Request(origin, { headers: {
  cookie: `__Host-student_session=${raw}`, origin, "x-csrf-token": value,
} });

it("[#865 canonical CSRF] uses domain-prefixed raw Session and padding-free SHA-256", async () => {
  expect(isCanonicalToken(expected)).toBe(true);
  expect(isCanonicalToken("A".repeat(42) + "B")).toBe(false);
  const digest = vi.spyOn(crypto.subtle, "digest");
  try {
    expect(await new StudentSessionCsrf(origin).validate(request())).toBe(true);
    expect(digest).toHaveBeenCalledExactlyOnceWith("SHA-256", new TextEncoder().encode("student-csrf-v1:" + raw));
  } finally { digest.mockRestore(); }
});

it("[#865 fixed-length compare] examines all characters for first, middle and final mismatches", async () => {
  for (const index of [0, 21, 42]) {
    const changed = expected.slice(0, index) + (index === 42 ? "E" : "A") + expected.slice(index + 1);
    expect(isCanonicalToken(changed)).toBe(true);
    const charCode = vi.spyOn(String.prototype, "charCodeAt");
    let result: boolean;
    let visited: number[];
    try {
      result = await new StudentSessionCsrf(origin).validate(request(changed));
      visited = charCode.mock.calls.slice(-86).map((args) => args[0]);
    } finally { charCode.mockRestore(); }
    expect(result).toBe(false);
    expect(visited).toEqual(Array.from({ length: 43 }, (_, position) => [position, position]).flat());
  }
});

it("[#865 config failure] rejects undefined origin before digest", async () => {
  const digest = vi.spyOn(crypto.subtle, "digest");
  try {
    await expect(new StudentSessionCsrf(undefined).validate(request())).rejects.toMatchObject({ code: "SERVICE_UNAVAILABLE" });
    expect(digest).not.toHaveBeenCalled();
  } finally { digest.mockRestore(); }
});

it("[#896 shared derivation] preserves the independent vector and rejects malformed raw input", async () => {
  expect(await createStudentSessionCsrfToken(raw)).toBe(expected);
  for (const value of ["", "A".repeat(42), "A".repeat(42) + "B", raw + "="]) {
    await expect(createStudentSessionCsrfToken(value)).rejects.toMatchObject({ code: "SERVICE_UNAVAILABLE" });
  }
});

it("[#896 shared validation] accepts issued tokens and rejects wrong, old and malformed values", async () => {
  const validator = new StudentSessionCsrf(origin);
  expect(await validator.validate(request(await createStudentSessionCsrfToken(raw)))).toBe(true);
  const next = "B".repeat(42) + "A";
  const nextRequest = request();
  nextRequest.headers.set("cookie", `__Host-student_session=${next}`);
  expect(await validator.validate(nextRequest)).toBe(false);
  nextRequest.headers.set("x-csrf-token", await createStudentSessionCsrfToken(next));
  expect(await validator.validate(nextRequest)).toBe(true);
  for (const value of [raw, expected + "=", expected.slice(1), "A".repeat(42) + "B"]) {
    expect(await validator.validate(request(value))).toBe(false);
  }
});
